sudo: required

services:
  - docker

before_install:
  - docker version
  - sudo apt-get -y install python-pip
  - sudo pip install docker==2.7.0 docker-squash
  - docker build -t mubox/logvac .

script: sudo test/run_all.sh

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/logvac .
  - docker-squash -t ${NAMESPACE}/logvac:squashed -f mubox/base --tmp-dir /var/tmp/squasher ${NAMESPACE}/logvac
  - docker tag ${NAMESPACE}/logvac:squashed ${NAMESPACE}/logvac:beta;
  - docker push ${REMOTE}${NAMESPACE}/logvac:beta;
  - if [ "$BRANCH" == "master" ]; then
    docker tag ${NAMESPACE}/logvac:squashed ${NAMESPACE}/logvac;
    docker push ${REMOTE}${NAMESPACE}/logvac;
    else
    docker tag ${NAMESPACE}/logvac:squashed ${NAMESPACE}/logvac:${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/logvac:${BRANCH//\//_};
    fi
